execution=browserstack
platform=ios

localurl=http://127.0.0.1:4723

deviceid=061B0E0A-29A2-4855-95DE-AC45E71634F0

bundleid=com.saucelabs.SwagLabsMobileApp


apppackage=com.swaglabsmobileapp


appactivity=com.swaglabsmobileapp.MainActivity


platformname=Android


browserstackbaseurl=https://hub.browserstack.com/wd/hub



#bs.app=bs://4dba649642473787ddf66891d0e0f7e43ea0558c
#bs.device=iPhone 15 Pro
#bs.osVersion=17.5
bs.app=bs://f78b9e4edb24407257622e54586bdce3dc9fe6ff
bs.device=Google Pixel 6
bs.osVersion=12.0
#emulator-5556

