execution=browserstack
platform=android

localurl=http://127.0.0.1:4723

deviceid=emulator-5554
bundleid=com.saucelabs.mydemoapp.rn
apppackage=com.swaglabsmobileapp
appactivity=com.swaglabsmobileapp.MainActivity
platformname=Android




sauce.username=your_username
sauce.accesskey=your_access_key
sauce.url=https://ondemand.us-west-1.saucelabs.com:443/wd/hub