execution=local
platform=android

localurl=http://127.0.0.1:4723

deviceid=emulator-5554
bundleid=com.saucelabs.SwagLabsMobileApp
apppackage=com.swaglabsmobileapp
appactivity=com.swaglabsmobileapp.MainActivity
platformname=Android







#bs.username=brahmendrajayara_zI9n7K
#bs.accesskey=9zCBA4RPLh4qsN9USceq
bs.app=bs://4dba649642473787ddf66891d0e0f7e43ea0558c
bs.device=iPhone 15 Pro
bs.osVersion=17.5
#bs://f78b9e4edb24407257622e54586bdce3dc9fe6ff
#Google Pixel 6
#12.0

