usernameandroid=//android.widget.EditText[@content-desc='test-Username']
usernameios=//XCUIElementTypeTextField[@name='test-Username']
passwordandroid=//android.widget.EditText[@content-desc='test-Password' and @text='Password']
passwordios=//XCUIElementTypeSecureTextField[@name='test-Password']
loginandroid=//android.view.ViewGroup[@content-desc='test-LOGIN' or @content-desc='LOGIN']
loginios=//XCUIElementTypeOther[@name='test-LOGIN']
policyandroid=new UiSelector().className("android.widget.ImageView").instance(4)
policyios=**/XCUIElementTypeOther[`name == "test-Toggle"`]
errorpath=//XCUIElementTypeStaticText[@name="Sorry, this user has been locked out."]
errorpathandroid=//android.widget.TextView[@text="Sorry, this user has been locked out."]
